### ISSUE TITLE
Divx to WebM: The AC-3 sound is converted to MONO sound.

### ISSUE THREAD

**Issue by te-con-miel** [danielgtaylor/arista#100]
Hello,

In divx with ac-3 sound, when I convert to webm, the sound resultant is mono.

Examples:

http://www.imagengratis.org/images/seleccin0ec8ce.png
http://www.imagengratis.org/images/seleccin003.png

**Comment by te-con-miel** [comment]
http://www.imagengratis.org/images/seleccin0jr9lj.png

arista-gtk -v
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
arista.presets [517]: DEBUG Loaded device Android (6 presets)
arista.presets [517]: DEBUG Loaded device Apple iOS (4 presets)
arista.presets [517]: DEBUG Loaded device Sony Playstation (2 presets)
arista.presets [517]: DEBUG Loaded device Nokia N Series (4 presets)
arista.presets [517]: DEBUG Loaded device DVD Player (3 presets)
arista.presets [517]: DEBUG Loaded device Web Browser (3 presets)
arista.presets [517]: DEBUG Loaded device Computer (4 presets)
/usr/bin/arista-gtk:373: GtkWarning: Theme file for default has no name

  self.window.show()
/usr/bin/arista-gtk:373: GtkWarning: Theme file for default has no directories

  self.window.show()
arista-gtk [2366]: DEBUG Increasing niceness by 5...
arista-gtk [1904]: DEBUG Saving preset to disk...
arista.queue [185]: DEBUG Found item in queue! Queue is Cola de conversión: [Queue entry /home/marcelo/Vídeos/Ironclad.2011.BDRiP.XViD-PSiG/Ironclad 2011 BDRiP XViD-PSiG.avi -> WebM webmmux -> /home/marcelo/Vídeos/Ironclad 2011 BDRiP XViD-PSiG.webm]
arista.discoverer [230]: DEBUG Obteniendo /home/marcelo/Vídeos/Ironclad.2011.BDRiP.XViD-PSiG/Ironclad 2011 BDRiP XViD-PSiG.avi
No accelerated IMDCT transform found
arista.transcoder [620]: DEBUG uridecodebin uri="file:///home/marcelo/Vídeos/Ironclad.2011.BDRiP.XViD-PSiG/Ironclad 2011 BDRiP XViD-PSiG.avi" name=dmux webmmux name=mux ! queue ! filesink name=sink location="/home/marcelo/Vídeos/Ironclad 2011 BDRiP XViD-PSiG.webm" filesrc location="/home/marcelo/Vídeos/Ironclad.2011.BDRiP.XViD-PSiG/Ironclad 2011 BDRiP XViD-PSiG.srt" ! subparse  ! txt. dmux. ! queue ! ffmpegcolorspace ! videorate !   textoverlay font-desc="Sans Bold 16" name=txt !  videoscale ! video/x-raw-yuv, width=(int)640, height=(int)352, framerate=(fraction)10000000/416667, pixel-aspect-ratio=(fraction)1/1\; video/x-raw-rgb, width=(int)640, height=(int)352, framerate=(fraction)10000000/416667, pixel-aspect-ratio=(fraction)1/1 ! vp8enc quality=10 threads=1 speed=2 ! tee name=videotee ! queue ! mux.video_%d dmux. ! queue ! audioconvert ! audiorate tolerance=100000000 ! audioresample ! audio/x-raw-int, width=(int)[ 8, 32 ], depth=(int)[ 8, 24 ], rate=(int)[ 8000, 96000 ], channels=(int)[ 1, 2 ]\; audio/x-raw-float, width=(int)[ 8, 32 ], depth=(int)[ 8, 24 ], rate=(int)[ 8000, 96000 ], channels=(int)[ 1, 2 ] ! vorbisenc quality=0.4 ! mux.audio_%d
No accelerated IMDCT transform found

**Comment by danielgtaylor** [comment]
Hmm, the command is saying channels can be 1 or 2. What happens if you edit the preset to only allow 2 channels and try encoding again?

**Comment by te-con-miel** [comment]
I'll try.

I'LL Comment the result soon.

**Comment by te-con-miel** [comment]
With '2 to 2' channles the audio resultant is in stereo 128kbs.

Thank you.
