### ISSUE TITLE
X11 crashes when starting transcode

### ISSUE THREAD

**Issue by milgner** [danielgtaylor/arista#125]
As soon as I start the transcoding process, I see, for about a second, the progress dialog and immediately after that my whole X11 session crashes.
This is Arista 0.9.7 on Fedora 16.
I can't find a really helpful error message, but maybe it's related to these messages appearing in my logs:

[90006.534547] gnome-shell[11382]: segfault at 546ed5008 ip 0000003e7fe5ff28 sp 00007fffc4150720 error 4 in libglib-2.0.so.0.3000.1[3e7fe00000+11e000]

**Comment by danielgtaylor** [comment]
Are you able to use Totem or other GStreamer-based applications?

**Comment by milgner** [comment]
Totem is working fine, I just tried it with the source video I wanted to transcode.

**Comment by danielgtaylor** [comment]
Hmm, does running 'arista-transcode inputfile.mp4' in a terminal work or does that crash as well? (replace inputfile.mp4 with your file name of course)

**Comment by milgner** [comment]
Running it from the Gnome terminal works, it seems to be a problem with the GUI somehow.

**Comment by milgner** [comment]
I'll try it on another computer this evening where there's almost exactly the same configuration except that I didn't install the proprietary AMD fglrx driver there. I have a hunch that the driver may cause some hiccups.

**Comment by milgner** [comment]
Everything's working fine on my other system. And since transcoding via command line works I'm guessing it's not a problem you can do anything about as the real cause is probably somewhere down the library chain... I'm closing the issue.
