### ISSUE TITLE
Unable to transcode under Debian

### ISSUE THREAD

**Issue by diega** [danielgtaylor/arista#13]
select any source
select any preset
click on 'add to queue'
got this message Cannot add item to queue because of missing elements!

Console output
arista.presets [369]: INFO Attempting to install elements: lame, xvidenc
arista.presets [385]: ERROR Installing elements not supported!

Digging into arista/presets.py I came up with this line returning false:
            if gst.pbutils.install_plugins_supported():
I understand this is gstreamer related but I couldn't found relevant information.

If you thinks is only debian packaging related I'll be report it to BTS without any trouble. 

Here are my deps in case you find it useful
    ii  gstreamer0.10-ffmpeg      0.10.10-1                 FFmpeg plugin for GStreamer
    ii  gstreamer0.10-plugins-bad 0.10.19-1                 GStreamer plugins from the "bad" set
    ii  gstreamer0.10-plugins-bas 0.10.29-4                 GStreamer plugins from the "base" set
    ii  gstreamer0.10-plugins-goo 0.10.23-4                 GStreamer plugins from the "good" set
    ii  gstreamer0.10-plugins-ugl 0.10.15-1                 GStreamer plugins from the "ugly" set
    ii  python                    2.5.4-9                   An interactive high-level object-oriented language (default versio
    ii  python-cairo              1.8.8-1+b1                Python bindings for the Cairo vector graphics library
    ii  python-dbus               0.83.1-1                  simple interprocess messaging system (Python interface)
    ii  python-gconf              2.28.1-1                  Python bindings for the GConf configuration database system
    ii  python-gobject            2.21.1-2                  Python bindings for the GObject library
    ii  python-gst0.10            0.10.18-2                 generic media-playing framework (Python bindings)
    ii  python-gtk2               2.17.0-2                  Python bindings for the GTK+ widget set
    ii  python-gudev              147.1-1                   Python bindings for gudev
    ii  python-nautilus           0.6.1-1                   Python binding for Nautilus components
    ii  python-notify             0.1.1-2+b2                Python bindings for libnotify
    ii  python-rsvg               2.30.0-1+b1               Python bindings for the RSVG library
    ii  python-simplejson         2.1.1-1                   simple, fast, extensible JSON encoder/decoder for Python

**Comment by danielgtaylor** [comment]
What does the output of this command say?

```
gst-inspect-0.10 | egrep "lame|xvid"
```

My output is as follows:

```
twolame:  twolame: TwoLAME mp2 encoder
lame:  lamemp3enc: L.A.M.E. mp3 encoder
lame:  lame: L.A.M.E. mp3 encoder
xvid:  xviddec: XviD video decoder
xvid:  xvidenc: XviD video encoder
```

**Comment by diega** [comment]
Here it goes:
    diego@sandia:~$ gst-inspect-0.10 | egrep "lame|xvid"
    twolame:  twolame: TwoLAME mp2 encoder
    diego@sandia:~$ 
Do you know what I have to do to get the other ones?

Edit:
I just found the other needed packages
gstreamer0.10-lame
gstreamer0.10-plugins-really-bad
Maybe will be useful to have them in the README file.
Thanks for your attention.

**Comment by danielgtaylor** [comment]
Added a note as of 37c53c6d46b226d3646c79a298a0c548177f3243

**Comment by bcinteractive** [comment]
I don't see this in Debian Squeeze.  Maybe you have an idea...
