### ISSUE TITLE
Pipeline errors after getting presets

### ISSUE THREAD

**Issue by db60462** [danielgtaylor/arista#148]
I am running Zorin 6 and had a working Arista before downloading the presets for "DVD Player" and DVD Player SVCD"   When trying o transcode a .avi movie to NTSC I get a pipeline errors "could not link lame2 to mux."   And if I try to code it to SVCD it comes back could not construct pipeline "unable to link videoscale3 to mpeg2enc3"   Any help please, it worked before these new presets.     I installed them thru the Arist "File" tag.

**Comment by danielgtaylor** [comment]
The preferences dialog has a 'Reset Presets' button you can try that will reset all presets to the defaults. If you have modified other presets or created new ones you may want to back those up first - they should live in ~/.arista/presets/.

**Comment by db60462** [comment]
That did it.. thanks for fast response.
