### ISSUE TITLE
Python scripts shebang lines

### ISSUE THREAD

**Issue by alessio** [danielgtaylor/arista#15]
I've applied the following patch [1] in Debian to fix the shebang lines of the scripts.
Please consider to apply it in order to allow python-support to generate the dependencies properly.

http://git.debian.org/?p=collab-maint/arista.git;a=blob;f=debian/patches/02-shebangs.patch;h=b244a02cf84e5ebd77a6acbef724c313cd183e0a;hb=HEAD

**Comment by danielgtaylor** [comment]
What happens if there is no /usr/bin/python? I thought /usr/bin/env was the proper way to do it so that the user's configured environment is used?

**Comment by alessio** [comment]
python-support relies on the shebangs to understand which version of python is needed.

For instance, if you put

```
#!/usr/bin/python2.5
```

at the beginning of a .py file (module or script), after installing it python-support will populate the Depends field of the package with something like the following:

```
Depends: python-support, python2.5
```

`#!/usr/bin/python` means "this works with all supported python versions", so python-support would behave differently and populate the Depends field with an unversioned python dependency.

**Comment by danielgtaylor** [comment]
Fixed in d11ec839722cabfa247665f36e3737a2033e74a6. The nautilus script doesn't get a line because it cannot be run from the shell.

**Comment by alessio** [comment]
Although it cannot be run from the shell, it must be interpreted and the shebang would just indicate which version of the interpreter should be used.

Adding #!/usr/bin/python is enough.

**Comment by danielgtaylor** [comment]
This isn't how embedding Python works though, see:
- http://docs.python.org/extending/embedding.html

The linked-in python.h and statically or dynamically linked python.so or DLL defines the version currently being used to run the embedded interpreter, not the scripts that are run by that interpreter.

In this case it means whatever Python version is linked with nautilus-python is the one that will be used, regardless of what is in my Python code.

I'm fine if this is required for Debian and you keep it in a separate patch, but I see no reason to put Debian-specific stuff upstream unless you can give me a valid non-Debian-specific reason to do so. None of the documentation I can find seems to indicate that there should be a shebang line in the Nautilus extension.

**Comment by alessio** [comment]
Ehy Daniel,

after some time spent to have a deeper look at other python packages I can say yes, you're right, the changes I've proposed seem unnecessary at all.

So please nevermind, I'll drop my patch even from the packaging with the next upload.

Thanks!
