### ISSUE TITLE
no run for arista

### ISSUE THREAD

**Issue by Nickness** [danielgtaylor/arista#154]
hi, i'm running Fedora 18 and i've just install arista but it doesn't work. Here is the feed-back from the terminal:

[nico@localhost ~]$ arista-gtk 
Traceback (most recent call last):
  File "/usr/bin/arista-gtk", line 45, in <module>
    import gconf
ImportError: No module named gconf

i do not know what to do. I followed all the istruction.
the only plugin that yum doesn't find is "gstreamer-plugins-bad-nonfree" but i don't think that is the problem. Right?

**Comment by danielgtaylor** [comment]
I believe this was fixed by installing all the dependencies listed at https://github.com/danielgtaylor/arista#dependencies so I'm closing the issue. Reopen if needed!

**Comment by Nickness** [comment]
python-cairo 
python-gobject 
python-gconf 
python-gstreamer 
gstreamer-plugins-bad-nonfree

these are not avaible trying to install with yum. The other package listed in the site are already installed to the last version.
am i losing something about python?

**Comment by danielgtaylor** [comment]
It's possible the packages are called something different in Fedora. Just search around. For example, I think python-gconf might be gnome-python-gconf or gnome-python2-gconf. Yum should have some way to search for keywords so that you can find all those packages.
