### ISSUE TITLE
Add MPEG-2 Transport Stream (M2TS) Container capability

### ISSUE THREAD

**Issue by flexiondotorg** [danielgtaylor/arista#16]
Hi,

I'd like to create MPEG-2 TS files for streaming to my PS3 via miniDLNA or Mediatomb. The advantage of M2TS containers on the PS3 is that you can include Dolby Digital (AC3) 5.1 audio and preserve the original audio quality. However, the PS3 can't play DTS audio stream in M2TS containers so DTS would require converting to AC3.

M2TS containers can include MPEG-2 or H.264 video (up to level 4.1).

I've created my own shell scripts to transcode Blu-Ray rips made with DumpHD and MakeMKV to M2TS with burned in subs and audio conversion to AC3. I'll be happy to assist since Arista is a much more flexible tool than my lash up :-)

Regards, Martin.

**Comment by danielgtaylor** [comment]
Martin,

As of http://github.com/danielgtaylor/arista-website/commit/28ad0149c6aa07dad9660f9a2752857c9f973e65 the website should now let you choose MPEG-TS and AC3 when creating a new preset. Please try it out and let me know if you have any issues.

**Comment by flexiondotorg** [comment]
Hi,

Thanks very much for adding this feature to the website. 

Regards, Martin.
