### ISSUE TITLE
Add AAC 5.1 audio transcoding or Dolby Digital and DTS

### ISSUE THREAD

**Issue by flexiondotorg** [danielgtaylor/arista#17]
Hi,

In order to preserve more of the original audio quality for my PS3 rips it would be great to add transcoding of Dolby Digital and DTS to AAC 5.1.

I have some experience of doing this via shell scripts and vairous tools suchs as ffmpeg, mplayer, faac, NeroAacEnc, sox, etc. The biggest hurdle is getting the discrete channel assignments correct as they are differ slightly for the various 5.1 formats. I've not developed using gstreamer so don't know if it has mechanisms to ease the channel assignment problem? Here are the 5.1 channels assignments for each audio format.

Format  Chan 0  Chan 1  Chan 2  Chan 3  Chan 4  Chan 5
5.1 WAV FL      FR      FC      LFE     SL      SR
5.1 AC3 FL      FC      FR      SL      SR      LFE
5.1 DTS FC      FL      FR      SL      SR      LFE
5.1 AAC FC      FL      FR      SL      SR      LFE
5.1 AIFF    FL      SL      FC      FR      SR      LFE

FL : Front Left
FC : Front Center
FR : Front Right
SL : Surround Left
SR : Surround Right
LFE : Low Frequency Effects (Sub)

I will be happy to assist in whatever way I can :-)

Regards, Martin.

**Comment by danielgtaylor** [comment]
I've talked to the upstream GStreamer guys and they have let me know that these mappings are already in place in GStreamer and happen automatically. As of http://github.com/danielgtaylor/arista-website/commit/b3acbe7d1c29e1c3f44cc1c7c3b54ee22b6907bb you can now set limits for the audio channels mappings on the Arista Transcoder website when creating a new preset. This functionality was always in the preset files, just not exposed on the website.

I currently don't do any error checking on the values, but default to 1 or 2 channels which should work with every audio codec. You can put in "1, 6" to allow 1, 2, or 5.1 channel audio, which should work with at least AC3 and AAC. I'm not sure about the other codecs.

Let me know if this works for you!

**Comment by flexiondotorg** [comment]
Hi,

I created my own presets by hand, prior to your feedback and confirm that it does work :-) Thanks for adding the option to the website.

Regards, Martin.
