### ISSUE TITLE
path for noarch nautilus-python extension

### ISSUE THREAD

**Issue by shaba** [danielgtaylor/arista#18]
if arista-nautilus.py is noarch, then need use path /usr/share/nautilus-python/extensions/ for install.
Path /usr/lib(64)/nautilus/extensions-2.0/python for arch depended extensions.

**Comment by danielgtaylor** [comment]
Do you have some official documentation that defines what these paths are for?

**Comment by shaba** [comment]
from http://git.gnome.org/browse/nautilus-python/tree/README

As of nautilus-python 0.7.0, scripts are also loaded from $XDG_DATA_DIR/nautilus-python/extensions,
which includes ~/.local/share and /usr/share (or whatever your $XDG_DATA_DIR is
set to).

**Comment by shaba** [comment]
and from http://git.gnome.org/browse/nautilus-python/commit/?id=c97253104e7d6b88803cbef529bd9e298fa8d9e3

As of nautilus 2.32, there will no longer be a ~/.nautilus folder, so we should take this opportunity to start looking for extensions in the more correct ( or )/nautilus-python/extensions folders. We will continue to look in the old folders to keep the migration comfortable for developers/users
- // Look in the new global path, $DATADIR/nautilus-python/extensions
- nautilus_python_load_dir(module, DATADIR "/nautilus-python/extensions");
- // Look in the old global path, /usr/lib(64)/nautilus/extensions-2.0/python
- nautilus_python_load_dir(module, NAUTILUS_EXTENSION_DIR "/python");

you can see, that old global path /usr/lib(64)/nautilus/extensions-2.0/python - arch depended.

**Comment by DimStar77** [comment]
Pull request 54 addresses this.
