### ISSUE TITLE
Ubuntu package depends on gstreamer-plugins-bad, should depend on gstreamer-plugins-bad OR gstreamer-plugins-bad-multiverse

### ISSUE THREAD

**Issue by Shnatsel** [danielgtaylor/arista#19]
Arista packages in Ubuntu repository and in Arista PPA depend on gstreamer-plugins-bad package, but should depend on gstreamer-plugins-bad OR gstreamer-plugins-bad-multiverse packages. Though Ubuntu currently allows both packages to be installed simultaneously, there's no guarantee that it will be so in the future. Moreover, ppa:gstreamer-developers/ppa contains packages that don't allow both gstreamer-plugins-bad and gstreamer-plugins-bad-multiverse to be installed simultaneously, and adding it breaks Arista package and forces its removal.

**Comment by danielgtaylor** [comment]
This is an upstream packaging issue it seems. Alessio, can you take a look at changing the deps?

**Comment by alessio** [comment]
Sorry for the delay, I'll take a look ASAP.

**Comment by alessio** [comment]
Fix committed.
Thanks!

**Comment by alessio** [comment]
Uploaded to natty.
