### ISSUE TITLE
V4l records in black & white...

### ISSUE THREAD

**Issue by owenix** [danielgtaylor/arista#2]
Card = kworld 115 
Driver = philips saa7134

Issue: Arista detects and records from the card the only problem is a black and white result. Card works as expected in XAW & TV time.

**Comment by danielgtaylor** [comment]
This might be a card with multiple outputs. I use the default video4linux input from GStreamer - what happens when you do something along the lines of e.g.

```
gst-launch-0.10 v4l2src device=/dev/video0 ! decodebin ! ffmpegcolorspace ! xvimagesink
```

That command plays video from my webcam, so I'd assume it's similar for your tuner card.

**Comment by danielgtaylor** [comment]
The latest release contains some changes to automatically select the stream and format of input devices like the webcam, cameras, and DVDs. Can you try again and see if this issue is still happening?

**Comment by owenix** [comment]
It didn't fix the issue in this release, but this works 

gst-launch-0.10 v4l2src device=/dev/video0 ! ffmpegcolorspace ! xvimagesink

Thanks for your time. This is a great program regardless of its ability to capture tv.

**Comment by danielgtaylor** [comment]
Strange. I can't imagine why it would be black and white, unless the capture device is outputting multiple streams and the way I run gst-launch is picking the wrong one. What about if you try this command:

```
gst-launch-0.10 uridecodebin uri=v4l2:///dev/video0 ! ffmpegcolorspace ! xvimagesink
```

I have a feeling the decodebin stuff might be picking the incorrect stream.

**Comment by danielgtaylor** [comment]
It's been a year with no response, so closing as unsolved for now.
