### ISSUE TITLE
How to Install preset from arista-0.9.3

### ISSUE THREAD

**Issue by Bharanik** [danielgtaylor/arista#20]
I am using Ubuntu 10.04 and by I have installed Arista 0.9.3 by using Synaptic.

Kindly help me in installing latest preset for Nokia 5230, 5530, 5800. 

Regards,
BharaniK.

**Comment by danielgtaylor** [comment]
Hey,

This is not possible as the preset formats have significantly changed. You'll need to update to the latest version. I've put in a request to have the latest release backported but so far haven't heard anything back. If you want to you can grab the source from http://www.transcoder.org/ and install it manually.

**Comment by Bharanik** [comment]
Its really great to see your comments. 

Thanks for the quick response. 

Kindly let me know how to install it manually as I am a new bee in Ubuntu / Linux. 

Regards,
BharaniK

**Comment by danielgtaylor** [comment]
You can download and extract the latest release (right click -> extract here), then open the folder and double click on arista-gtk. That will run the latest version from the download. To actually install it you need to open a terminal and navigate to the directory and run the install:

```
cd /path/to/arista-0.9.5/
sudo python setup.py install --install-layout=deb
```

**Comment by Bharanik** [comment]
Thanks a Ton.

Regards,
BharaniK

**Comment by Bharanik** [comment]
Successfully installed Arista's new version and able to add new preset also.

I have converted a video file (.avi) to Nokia 5530 compatible (.mp4) using Arista. 
However Nokia 5530 is not at all recognizing the file???
I did any thing wrong?

Regards,
BharaniK

**Comment by danielgtaylor** [comment]
I'm don't think you did anything wrong. These presets are contributed by other people and I don't own most of these devices so I can't really test when things go wrong. I suggest you go to Edit -> Preferences, click on Presets, then find the preset in the list and click on the About button to get the author's name and email. Maybe he can help you as you both own similar devices?

**Comment by Bharanik** [comment]
Thank you...
