### ISSUE TITLE
Trancode Nicely?

### ISSUE THREAD

**Issue by CarlGWatts** [danielgtaylor/arista#23]
Could the background transcodes be nice'd by default?
I really like the simplicity of cleanliness of Arista, good job.
Oh, and could there be a "Go" or "Add to Queue" action button below the "Settings" buttons? I know there is the "Add to Queue" menu item and toolbar button but I always turn toolbars off and the natural order of using the GUI is 1) "Settings" buttons 2) "Add to Queue" then possibly the "Queue" list so it would be nice if the GUI elements were in that order from top to bottom.
Again, create job! :)

**Comment by danielgtaylor** [comment]
I think that if you nice arista-gtk itself you will get the behavior you want. I'm not sure I can do just jobs as they aren't a separate process per-se. Instead I use the GStreamer framework as a library.

Re: the extra button, I will look into this. I'm unhappy with the current layout and have been trying for months to come up with a better design that makes sense. I dislike the idea of having functionality duplicated within the window and the toolbar, but I'll keep working on it.

**Comment by danielgtaylor** [comment]
Niceness should be +5 by default as of 1c538a5, and the UI has changed considerably to be more user friendly :-)
