### ISSUE TITLE
App icon sizes

### ISSUE THREAD

**Issue by monreal** [danielgtaylor/arista#26]
Currently, arista has:
- icon.svg => 64x64 pixels
- icon-small.svg => 14x14 pixels

For a nice and non-blurry experience it needs the following sizes: 16, 22/24, 32, 48, 256
If you agree, we can ask for shiny Tango artwork from [1]

[1] http://live.gnome.org/GnomeArt/ArtRequests

**Comment by danielgtaylor** [comment]
I have put up a request page on there. Let's see if anybody wants to help :-)

**Comment by danielgtaylor** [comment]
We now have a nice new shiny icon, but only at a single scalable size. In the future we may get different sizes!
