### ISSUE TITLE
Error icon

### ISSUE THREAD

**Issue by monreal** [danielgtaylor/arista#27]
The icon metaphor you use for "error" is what GNOME uses for "delete", which is a bit confusing.

Ideally, arista would just use the theme icon "dialog-error" instead, which is the freedesktop icon name for the GTK build-in icon "gtk-dialog-error"[1].

IIRC GTK can fall back to the build-in icon if "dialog-error" does not exist, i.e. if the user does not run arista from a desktop that supports the freedestkop icon spec (twm? _g_)

[1] http://library.gnome.org/devel/gtk/2.13/gtk-Stock-Items.html#GTK-STOCK-DIALOG-ERROR:CAPS

**Comment by danielgtaylor** [comment]
I'm not sure where this happens. Every dialog I create seems to use gtk.MessageDialog(..., type=gtk.MESSAGE_ERROR, ...) which is defined as the icon you are referencing. Can you give an example and how to reproduce it?

**Comment by monreal** [comment]
arista-gtk, line 1141
icon = arista.utils.get_path("ui/error.svg")

**Comment by danielgtaylor** [comment]
Ah, thanks for pointing that out. 9ee47b9b987eb8aa1c561d07a3a3b2141dba867f should fix the issue by always using the theme's "dialog-error" icon like you suggested. I've tested it and it does indeed use the theme icon.
