### ISSUE TITLE
Error converting divx Video to PAL DVD

### ISSUE THREAD

**Issue by c72578** [danielgtaylor/arista#30]
The error message says:
Unable to construct pipeline! Could not link lame0 to mux

Version of Arista Transcoder: 0.9.5
OS: Ubuntu Lucid

**Comment by danielgtaylor** [comment]
Can you provide the file that causes this?

**Comment by Tschew** [comment]
I have the same problem with any file I can think of, here a sample debug output from the latest snapshot I could find.

bartek@chronos:~/downloads/apps/danielgtaylor-arista-3ae2f9f$ ./arista-gtk -v
inputs [40]: DEBUG Falling back to HAL device discovery
arista.presets [450]: DEBUG Loaded device Android Phone (4 presets)
arista.presets [450]: DEBUG Loaded device Computer (4 presets)
arista.presets [450]: DEBUG Loaded device Web Browser (3 presets)
arista.presets [450]: DEBUG Loaded device Android Phone (3 presets)
arista.presets [450]: DEBUG Loaded device Computer (4 presets)
arista.presets [450]: DEBUG Loaded device DVD Player (3 presets)
arista.presets [450]: DEBUG Loaded device Apple iPad (2 presets)
arista.presets [450]: DEBUG Loaded device Apple iPhone / iPod (3 presets)
arista.presets [450]: DEBUG Loaded device Nokia N Series (3 presets)
arista.presets [450]: DEBUG Loaded device Sony Playstation 3 (2 presets)
arista.presets [450]: DEBUG Loaded device Sony PSP (2 presets)
arista.presets [450]: DEBUG Loaded device Web Browser (3 presets)
arista.queue [185]: DEBUG Found item in queue! Queue is Transcode queue: [Queue entry /home/bartek/Movies/The.Big.Bang.Theory.S03E03.The.Gothowitz.Deviation.HDTV.XviD-FQM.avi -> PAL DVD ffmux_dvd -> /home/bartek/Desktop/The.Big.Bang.Theory.S03E03.The.Gothowitz.Deviation.HDTV.XviD-FQM.mpg]
arista.discoverer [230]: DEBUG Discovering /home/bartek/Movies/The.Big.Bang.Theory.S03E03.The.Gothowitz.Deviation.HDTV.XviD-FQM.avi
arista.transcoder [565]: DEBUG uridecodebin uri="file:///home/bartek/Movies/The.Big.Bang.Theory.S03E03.The.Gothowitz.Deviation.HDTV.XviD-FQM.avi" name=dmux ffmux_dvd name=mux ! queue ! filesink name=sink location="/home/bartek/Desktop/The.Big.Bang.Theory.S03E03.The.Gothowitz.Deviation.HDTV.XviD-FQM.mpg" dmux. ! queue ! ffmpegcolorspace ! videorate !  videoscale ! video/x-raw-yuv, width=(int)624, height=(int)352, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1\; video/x-raw-rgb, width=(int)624, height=(int)352, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1 ! mpeg2enc format=9 bitrate=4000 ! tee name=videotee ! queue ! mux.video_%d dmux. ! queue ! audioconvert ! audiorate ! audioresample ! audio/x-raw-int, width=(int)[ 8, 24 ], depth=(int)[ 8, 24 ], rate=(int)[ 8000, 96000 ], channels=(int)[ 1, 2 ]\; audio/x-raw-float, width=(int)[ 8, 24 ], depth=(int)[ 8, 24 ], rate=(int)[ 8000, 96000 ], channels=(int)[ 1, 2 ] ! lame bitrate=128 ! mux.audio_%d

**Comment by miko** [comment]
I can confirm this also (same OS, version). For dvd it works for divx, but does not work for PAL/NTSC (so, avimux works, ffmux_dvd does not). Source files are *.MOV from my canon 450D. In my ubuntu 10.10 RC I have installed gstreamer0.10-plugins-ugly-multiverse instead of gstreamer0.10-lame

**Comment by miko** [comment]
Additional info: gst-launch-0.10 with the same parameter line gives exactly the same error, while 
ffmpeg -i file.MOV -target pal-dvd FILE.mpeg
works.

**Comment by c72578** [comment]
Here are trailers in divx format, which can be used for testing:
http://www.divx-digest.com/movies/previous_trailers.html
Would be nice, if this issue could be fixed.

**Comment by ManuelZ** [comment]
Same error, different system:
Arista Transcoder 0.9.6
Archlinux Kernel 2.6.38

Error: Unable to construct pipeline! could not link lame0 to mux
General
Complete name                    : /home/usuario/Documentos/Game of thrones S01 E01 720.mkv
Format                           : Matroska
File size                        : 1.46 GiB
Duration                         : 1h 1mn
Overall bit rate                 : 3 385 Kbps
Encoded date                     : UTC 2010-02-22 21:41:29
Writing application              : no_variable_data
Writing library                  : no_variable_data

Video
ID                               : 2
Format                           : AVC
Format/Info                      : Advanced Video Codec
Format profile                   : High@L3.1
Format settings, CABAC           : Yes
Format settings, ReFrames        : 3 frames
Muxing mode                      : Container profile=Unknown@3.1
Codec ID                         : V_MPEG4/ISO/AVC
Duration                         : 1h 1mn
Bit rate                         : 2 994 Kbps
Width                            : 1 280 pixels
Height                           : 720 pixels
Display aspect ratio             : 16:9
Frame rate                       : 23.976 fps
Color space                      : YUV
Chroma subsampling               : 4:2:0
Bit depth                        : 8 bits
Scan type                        : Progressive
Bits/(Pixel*Frame)               : 0.135
Stream size                      : 1.26 GiB (87%)
Writing library                  : x264 core 85 r1442tw
Encoding settings                : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=30 / sliced_threads=0 / nr=0 / decimate=1 / mbaff=0 / constrained_intra=0 / bframes=6 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=1 / wpredb=1 / wpredp=0 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=2994 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                         : English

Audio
ID                               : 1
Format                           : AC-3
Format/Info                      : Audio Coding 3
Mode extension                   : CM (complete main)
Codec ID                         : A_AC3
Duration                         : 1h 1mn
Bit rate mode                    : Constant
Bit rate                         : 384 Kbps
Channel(s)                       : 6 channels
Channel positions                : Front: L C R, Side: L R, LFE
Sampling rate                    : 48.0 KHz
Bit depth                        : 16 bits
Stream size                      : 169 MiB (11%)

**Comment by danielgtaylor** [comment]
This issue should now be fixed in trunk with the DVD preset version 1.2

**Comment by c72578** [comment]
Works fine for me now. Thanks for the fix!
