### ISSUE TITLE
Automaticaly add subtitles when possible..

### ISSUE THREAD

**Issue by cristianfere** [danielgtaylor/arista#33]
If you add a video in Queue and it have in same directory a subtitle with same name (Example: video.avi and video.srt), automaticaly add/merge the subtitle on the conversion job.

I believe this feature need only one interface change: One checkbox in the Preferences Window for enable and disable it. 

Thanks!!

**Comment by LinuxReign** [comment]
That would be nice indeed

**Comment by danielgtaylor** [comment]
Merged into trunk from cristianfere's fork. Thanks for the commit!
