### ISSUE TITLE
Nokia N800/810 preset

### ISSUE THREAD

**Issue by brashley46** [danielgtaylor/arista#39]
is set to transcode to .m4v, which none of the media players on my N800 will recognize. Every time I use Arista I must reset manually to .avi ... and when I tried to create a preset I did not know the parameters to set. Help?

**Comment by danielgtaylor** [comment]
You can now modify the presets yourself from within Arista as of a few days ago. That should fix issues like this :-)

**Comment by brashley46** [comment]
On 11-06-16 05:07 PM, danielgtaylor wrote:

> You can now modify the presets yourself from within Arista as of a few days ago. That should fix issues like this :-)
> 
> How do I do that? I'm running the December release (0.9.6) on a Ubuntu
> 11.04 Natty Narwhal system.

## 

B. Ross Ashley http://brashley46.livejournal.com http://brashley46.no-ip.info
"It would be too painful to think that there are worlds somewhere
where I got everything right."  Sulien, in _The King's Name_, by Jo Walton
Registered Linux user # 402119
