### ISSUE TITLE
Minimize to tray & NotifyOSD

### ISSUE THREAD

**Issue by fcsonline** [danielgtaylor/arista#4]
Hello,

I think it might be interesting if we could minimize Arista to gnome's tray, while it's working. 
A link: http://www.mail-archive.com/tracker-list@gnome.org/msg00669.html

Another improvement could be that when I finish each of the jobs in the queue, a message will be displayed with NotifyOSD. 
A link: https://wiki.ubuntu.com/NotificationDevelopmentGuidelines

If I have a moment try to create a patch for you to evaluate.

Regards

**Comment by danielgtaylor** [comment]
Thanks for the ideas! The tray is a very touchy subject... I'm not sure about that just yet because it's easy enough to just minimize the application. The NotifyOSD idea I love though, so I implemented it as of:

http://github.com/danielgtaylor/arista/commit/8fc87dda85ea7a1f1d172365efad4c1f99b1cf63

Check it out and let me know what you think.

**Comment by fcsonline** [comment]
Oh! A very quick response. This afternoon we'll try this new version, and give you feedback.

Thanks!

**Comment by danielgtaylor** [comment]
If you have any trouble getting the trunk version up and running you can see it in action here:

http://www.transcoder.org/screenshots/

I'm going to close this and open a new ticket for the tray stuff (but we'll use the Indicator Applet I think).

**Comment by fcsonline** [comment]
When I remove a job from the queue, the message that the job has finished appears.

I think that it is not a normal behavior.

**Comment by danielgtaylor** [comment]
Whoops, reopened. Will try and fix and let you know.

**Comment by danielgtaylor** [comment]
This should fix it: 

http://github.com/danielgtaylor/arista/commit/d57becf2afa51d6fd529cc86f5ea6ffebf2da5b5
