### ISSUE TITLE
Add mimetypes to .desktop

### ISSUE THREAD

**Issue by karlrelton** [danielgtaylor/arista#40]
Adding the following line to arista.desktop allows nautilus to give the user the choice of opening arista when the user inserts their dvd disk (nautilus pops up a dialog, or can be set to always open a certain program).

MimeType=x-content/video-dvd;x-content/video-vcd;x-content/video-svcd;

Keep up the good work on this useful program!

**Comment by danielgtaylor** [comment]
Added in https://github.com/danielgtaylor/arista/commit/e21e264b6c42d489abfa8504fde376f7e28c8fcc
