### ISSUE TITLE
Preset information

### ISSUE THREAD

**Issue by corneil** [danielgtaylor/arista#45]
The presets does not show any information indicating the target resolution of the transcoding / conversion.
It would be really helpful if the presets displayed information indicating the target resolution and what adjustments are being made like scaling up or down or padding.

**Comment by danielgtaylor** [comment]
I'm working on a dialog for this that will be similar to the input options dialog.

**Comment by brunetton** [comment]
Indeed, would be really usefull !

**Comment by danielgtaylor** [comment]
This is now implemented in trunk :-)

**Comment by brunetton** [comment]
Great new !
Thanks
