### ISSUE TITLE
Android encoding problem with gstreamer-plugins-bad 0.10.16

### ISSUE THREAD

**Issue by mdeslaur** [danielgtaylor/arista#46]
Ever since updating to gstreamer-plugins-bad 0.10.16 in Ubuntu Maverick, encoding has been broken on my Nexus One. It seems 0.10.16 now encodes videos as Main profile instead of Baseline profile, which makes them choppy and stutter on the Nexus One.

Although I can work around the issue by adding "profile=1" to the Android profile, I don't think that would work for people running Arista with older gstreamer-plugins-bad releases.

Is this a regression in gstreamer-plugins-bad? Should this be fixed in Arista? If so, how?

**Comment by mdeslaur** [comment]
Whoops...I meant gstreamer-plugins-ugly, not gstreamer-plugins-bad.

**Comment by danielgtaylor** [comment]
Hmm, the profile for phones should probably always be Baseline anyway. x264enc has supported the profile option for a long time so this shouldn't break previous versions.

**Comment by danielgtaylor** [comment]
I've updated all the Android presets for the latest release, but won't retroactively update older releases due to the GStreamer version issue!
