### ISSUE TITLE
arista-transcode command-line not converting xvid on ubuntu 10.10

### ISSUE THREAD

**Issue by jimirn** [danielgtaylor/arista#47]
I hope this is enough info to get someone with more python knowledge than me to look into this.

Using latest arista - 0.9.5
Using file:
test.avi: RIFF (little-endian) data, AVI, 624 x 352, 23.98 fps, video: XviD, audio: MPEG-1 Layer 3 (stereo, 48000 Hz)

arista-gtk converts the file without error.
arista-transcode throws an error when executing:

arista-transcode -d android -v test.avi
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
arista.presets [450]: DEBUG Loaded device Sony PSP (2 presets)
arista.presets [450]: DEBUG Loaded device Sony Playstation 3 (2 presets)
arista.presets [450]: DEBUG Loaded device Apple iPad (2 presets)
arista.presets [450]: DEBUG Loaded device Nokia N Series (3 presets)
arista.presets [450]: DEBUG Loaded device Web Browser (3 presets)
arista.presets [450]: DEBUG Loaded device Computer (4 presets)
arista.presets [450]: DEBUG Loaded device Android Phone (3 presets)
arista.presets [450]: DEBUG Loaded device Apple iPhone / iPod (3 presets)
arista.presets [450]: DEBUG Loaded device DVD Player (3 presets)
arista.presets [450]: DEBUG Loaded device HTC Desire (1 presets)
arista.presets [450]: DEBUG Loaded device Nokia N Series (4 presets)
arista.presets [450]: DEBUG Loaded device Web Browser (3 presets)
arista.presets [450]: DEBUG Loaded device Computer (4 presets)
arista.presets [450]: DEBUG Loaded device Android Phone (6 presets)
arista.queue [185]: DEBUG Found item in queue! Queue is Transcode queue: [Queue entry test.avi -> Samsung Galaxy S mp4mux -> test-android.mp4]
arista.discoverer [230]: DEBUG Discovering test.avi
Encoding test.avi for android (default) failed!
Not a recognized media file!

**Comment by umonkey** [comment]
I also have this problem, but I don't think it's related to xvid: I'm unable to transcode OGG videos too.

**Comment by AkeemMcLennon** [comment]
This is a bit of a late response, but I think the problem is that Arista only seems to recognize absolute paths.  The simple solution is to use an absolute path instead of a relative one.  However, I think I have fixed this with bluelaguna/arista@4f7c05acf8799d1c11f0

**Comment by umonkey** [comment]
This does help, thank you Akeem!
