### ISSUE TITLE
remove black bars / cropping

### ISSUE THREAD

**Issue by ghost** [danielgtaylor/arista#50]
hello

I can't see an option to trim away black bars/edges in the encode process. Is this available? If not, can it be added? For reference, Handbrake, OGMRip and Thoggen apps offer this feature.

**Comment by danielgtaylor** [comment]
This should be doable with a crop filter. The latest release supports arbitrary transforms and filters in presets. I'll see about adding something for it to the UI.

**Comment by ghost** [comment]
wonderful, I look forward to this. Will you be offering auto cropping logic, as well as user defined crop rules?
