### ISSUE TITLE
transcoding a DVD

### ISSUE THREAD

**Issue by keberhart** [danielgtaylor/arista#52]
When attempting to transcode a certain DVD with the GUI it crashes.

When running arista-transcode -s dvd:// from the command line I receive this error.

 File "/usr/lib/python2.6/dist-packages/arista/discoverer.py", line 351, in _notify_caps_cb
    self.videowidth = caps[0]["width"]
KeyError: 'width'

I haven't audited the code very much so don't have any hints for you,

**Comment by danielgtaylor** [comment]
It looks like the DVD is likely providing non-video caps as well as video caps and I'm using the wrong ones. I might need to filter the caps somehow to make sure I get the ones I need...

**Comment by danielgtaylor** [comment]
The caps-filtering is now in trunk and this issue should be fixed. If none of the caps work then it's likely the source isn't supported yet by GStreamer for any number of reasons.

**Comment by keberhart** [comment]
Thank you for your hard work.

On Thu, Jun 16, 2011 at 8:05 AM, danielgtaylor
reply@reply.github.com
wrote:
