### ISSUE TITLE
SSA Subtitle Support

### ISSUE THREAD

**Issue by AkeemMcLennon** [danielgtaylor/arista#58]
A lot of MKV files nowadays seem to use SSA / ASS for their subtitle format.  Unfortunately, Arista only seems to support the srt subtitle format.   After skimming through a few gstreamer docs,  I've proposed a temporary solution in bluelaguna/arista@42a3f52ef858ebec43d8265702a4490e3c348d84

However, this is based on the extremely limited knowledge I gained about gstreamer from last night and therefore has serious drawbacks as described in my notes

**Comment by danielgtaylor** [comment]
This patch was pulled in a while ago - closing ticket.
