### ISSUE TITLE
HTC Desire preset gives videos that Android cannot play

### ISSUE THREAD

**Issue by Hooloovoo** [danielgtaylor/arista#65]
I'm using an HTC Desire with Froyo 2.2 (official HTC update).

I used the "HTC Desire" preset:
http://www.transcoder.org/media/presets/desirebest.tar.bz2
to transcode some vob files into HTC Desire videos.

When I copied these into a "Video/subdir/" folder, they show up on the device as grey squares, but if you click on them, it gives the following error:
"Cannot play video
Sorry, this video cannot be played."

**Comment by Hooloovoo** [comment]
I'll try with the "Android" preset when I get home. I didn't realise that it covered the Desire as well, because there was a separate preset for that. Perhaps the individual phone presets should be deleted now that there is a generic one.

**Comment by Hooloovoo** [comment]
I used the Android preset to transcode the same videos and these all worked perfectly. Please delete the "HTC Desire" preset from the list to avoid confusion. Thanks for a great product!

**Comment by clem11388** [comment]
This is also true for the Droid / MIlestone preset. I don't know if this is the same issue though. So I will be creating a new "Issue" thread named "Droid / Milestone".

**Comment by Hooloovoo** [comment]
This is still the case, can you please delete the Desire preset?

**Comment by danielgtaylor** [comment]
I believe this is now fixed in trunk by manually setting the profile for android presets. They should work again :-)
