### ISSUE TITLE
Not a recognized media file!

### ISSUE THREAD

**Issue by marcelinolnec** [danielgtaylor/arista#67]
Hi!

I usually prefer the shell version of some programs as it is easier to assign the task to a batch job to run in the background using less cpu and resources.
The arista-transcode was perfect to me to put some movies in my ipod. The command was:
arista-transcode -d ipod input_file.avi output_name.m4v
But now this is not working. I get the "Not a recognized media file!" error
HELP please.
P.S. the gtk version works like a charm...

**Comment by AkeemMcLennon** [comment]
See Issue #47.
