### ISSUE TITLE
DTS being converted to stereo

### ISSUE THREAD

**Issue by dansin** [danielgtaylor/arista#68]
I'm trying to convert a ripped bluray so I can reduce the file size.  It is currently an MKV file created with MakeMKV.  Every time I put it through Arista the video output is perfect but the DTS sound always converts to stereo.  I'm using the 'Computer' preset which has the 1, 6 audio channels in the configuration.  Any ideas?

Thanks in advance

Dan

**Comment by danielgtaylor** [comment]
The GStreamer encoder element being used may only support two audio channels, so it will be downsampled regardless of what the audio channel settings in the preset are. This would have to be updated upstream in GStreamer, and then Arista would automatically make use of the higher channels.
