### ISSUE TITLE
Building a preset for XBMC4XBOX: how to set a maximum bitrate?

### ISSUE THREAD

**Issue by Mikywing** [danielgtaylor/arista#71]
Hi all! After solving my problems with arista and gstreamer i need to know a thing.

How can i set a maximum bitrate value in a preset? I'm trying to create a XBMC4XBOX preset to get 720p videos using mpeg4ASP encoding (the preset provided in the download page only does a generic, low quality encoding), but i need to set a maximum bitrate value of 5000kbit or else video playback hangs for few secs in complex scenes. How can i achieve that?

**Comment by Mikywing** [comment]
After some investigating (and thanks to gstreamer-utils, especially gst-inspect) i got that xvid does not provide an option to use a fixed maximum bitrate. I'm using ffenc-mpeg4 instead to create the preset since it does provide the option i need and it's even faster while encoding!

**Comment by brulzki** [comment]
Could you share your working presets? I've been trying to get a working preset for the xbox.

**Comment by danielgtaylor** [comment]
I believe there is now an XBMC preset on transcoder.org, so I'm closing this issue for now.

**Comment by brulzki** [comment]
The comment above suggested that Mikywing had a preset that does better quality than the one on transcoder.org.
I used to be able to get good encodes with x264 (but not using gstreamer) which worked on the xbox, but its not been working for me for a while and I've not yet figured out what the best encoding options are that would work. Mikywing's sounded promising...

**Comment by Mikywing** [comment]
Exactly, the xbmc4xbox preset on the website is quite limited and outdated. I was working on a newer one able to convert 720p videos for the old and limited xbox hardware. Unluckily I accidentally lost the work i had done, but i remember that after some tests i found the xbox ffenc-mpeg4 limit at 6000-6500 kbps with the options "rc-maximum-bitrate" and "rc-video-bufsize" (i'm not sure they're the exact names). I never released the preset because generally (and especially when the bitrate reached that limit) the resulting video was "blocky" and did not satisfy me, even if it was a huge step forward than the actual preset. I used ffenc-mpeg4 basic settings, except for the two i mentioned to limit the maximum bitrate, so i believe that playing around a bit should improve a lot the quality, but i haven't neither the time (cause of exams) or the knowledge to do so...
Oh i also tried xvid but it only allows a way loose bitrate limit and takes much more time to convert so its not a good option for xbmc
