### ISSUE TITLE
setup.py byte-compiling issues

### ISSUE THREAD

**Issue by ford-prefect** [danielgtaylor/arista#73]
The new setup.py bits that byte-compile the installed py files should be optional (at least). In Gentoo, we handle these at the packaging level, so it's redundant.

More importantly, the byte-compile step is not prefix aware, so when installing into a prefix (setup.py --root, aiui), it still tries to byte-compile the system version.

**Comment by danielgtaylor** [comment]
Is this still true with the latest trunk? I recall there being a fix for that so that virtualenv could also be used...

**Comment by ford-prefect** [comment]
I found that I also needed something like this: http://people.collabora.co.uk/~arun/0001-Respect-system-byte-compiling-settings.patch

**Comment by danielgtaylor** [comment]
Patch applied in ae8fb6b. Thanks for the fix :-)
