### ISSUE TITLE
Android Droid / Milestone preset does not play on my Droid 1

### ISSUE THREAD

**Issue by clem11388** [danielgtaylor/arista#74]
I don't know why but converting from an AVI file to this preset did not play. I don't know why. The video codec in the properties is "H.264 / AVC". And the audio codec is listed as "MPEG-4 AAC audio". And the video file format suffix is .mp4.

And both of these are the exact same codecs that are used in the "iPhone / iPod touch" preset and this preset plays fine. But the video file format suffix is .m4v. 

Why is this??

**Comment by danielgtaylor** [comment]
Can you try Arista from git and confirm whether this is still an issue?
