### ISSUE TITLE
WebM plays as .mp4

### ISSUE THREAD

**Issue by clem11388** [danielgtaylor/arista#75]
Yes and the file is named as "Episode 306.webm" . but when VLC or Movie player plays it. The title is "Episode 306.mp4". 

The video codec is listed as "VP8 video" and the audio codec is "Vorbis". So why is the title that is embeded into the details of the video (not the name of the file) is listed as "Episode 306.mp4" ? I know WebM is just now starting to be implemented but this seems like a simple thing. Outside of this small detail, the video played well and converted at the same speed as any of the other formats. 

One not is that it made the output video resolution larger than the input video's resolution was. So at the full size of the video it was grainy. But making the player smaller to be the same size it would have been with the smaller resolution makes the video look fine. Just a side for the developers.

   God bless guys!

   [update] before I said the video played fine. But on watching more of the video, there were places where the video became very garbled and messed up to the point that you can't even see what is happening at all. Its only the video that does that. The audio is perfectly fine. And it only happens for about 4 to 5 seconds of the 24 minute long video. But definitely something the developers need to work on. Though I'm not sure if this is a problem with the Arista Converter or if its the WebM codect its self. Where the latter would require Google to do more development on WebM, since they do "own" it.

**Comment by danielgtaylor** [comment]
What you are seeing is likely just metadata in the file (some kind of "title" attribute). It's actually VP8/Vorbis in WebM, but showing you the metadata which for some reason contained the .mp4 in the name.

The VP8 encoder is still a work in progress and with each GStreamer update it should get better, but it's outside the scope of Arista itself!
