### ISSUE TITLE
Support for DVD directory structure as input

### ISSUE THREAD

**Issue by mdz** [danielgtaylor/arista#76]
Given a folder containing a DVD directory structure, it would be useful to be able to use that as input to arista, in the same way that a DVD drive can be. Thoggen has code to support this.

**Comment by danielgtaylor** [comment]
I'm afraid this isn't easy to support through GStreamer from what I can tell. I'll take a closer look at Thoggen but I know it links with various other libraries (like libdvdread) that would require C code (Arista is written entirely in Python).

**Comment by danielgtaylor** [comment]
This is also a duplicate of https://github.com/danielgtaylor/arista/issues/51
