### ISSUE TITLE
Is possible to make a preset for two pass encoding?

### ISSUE THREAD

**Issue by Mikywing** [danielgtaylor/arista#77]
Hi all! As the topic title tells, is possible to make a preset able to do a two-pass video encoding? If yes how?

I'm quite new at gstreamer, so i don't know if it's possible to parse two commands (pass 1 and following pass 2) in the same pipeline or consecutively in the same preset.

**Comment by danielgtaylor** [comment]
Open one of the preset files in a text editor and you can add multiple passes, e.g:

```
...
"vcodec": {
    ...
    "name": "x264enc",
    "passes": [
        "pass=1 ... threads=0",
        "pass=2 bitrate=512 ... threads=0"
    ],
    ...
},
...
```

**Comment by danielgtaylor** [comment]
You can now do this in Arista itself in the video or audio options by separating passes with a semicolon.
