### ISSUE TITLE
Missing json module with Python 2.5

### ISSUE THREAD

**Issue by alessio** [danielgtaylor/arista#8]
Hello,

when I run arista-gtk with python2.5 I get the following error message:

sbaturzio@satellite:~$ arista-gtk
Traceback (most recent call last):
  File "/usr/bin/arista-gtk", line 1560, in <module>
    arista.init()
  File "/usr/share/arista/arista/**init**.py", line 49, in init
    import presets
  File "/usr/share/arista/arista/presets.py", line 43, in <module>
    import json
ImportError: No module named json

That's due to the lack of json module in python2.5 (on the contrary python2.6 provides it).

On Debian testing we have the 2.5 as python default version, so please could you adjust the code to add support for that?

Thanks in advance, and keep up the great work!

**Comment by danielgtaylor** [comment]
Whoops, check latest trunk and let me know if it fixes things. Added new dependency for Python <2.6: python-simplejson. New release will be coming out this week to fix all these little issues, and it should be fairly stable. Then I'll start working on new features again and won't do another release for a while.

**Comment by alessio** [comment]
Daniel, thanks for the fast reply.

I cannot test it now, have you tried it?

Are you sure that simplejson provides all needed modules?

**Comment by danielgtaylor** [comment]
This is the same module I use on my server to parse the preset files for transcoder.org. Basically the simplejson module is a backport of the Python 2.6 json module to other versions of Python (so they are exactly the same).

Do please confirm and close if everything is working okay.
