### ISSUE TITLE
[feature request] Remove HAL dependency

### ISSUE THREAD

**Issue by solsticedhiver** [danielgtaylor/arista#80]
hi.
In recent linux distro, hal is not lauchned by default because it is not needed anymore. So I have to launch manually HAL for arista to work.

HAL has been deprecated if I am right (?). So if you could find a way to remove its use and find something else to use instead ???

**Comment by danielgtaylor** [comment]
If you have python-gudev installed it will use udev rather than dbus/HAL for device discovery. HAL support is left in for older distros that don't have udev yet!
