### ISSUE TITLE
README and Fedora specific installation info

### ISSUE THREAD

**Issue by valentt** [danielgtaylor/arista#86]
Hi,
there is no Fedora specific info regarding how to install so I can help you to add some Fedora specific info.

Fedora users first need to enable RPM Fusion repo because they won't have dependencies for Arista (http://rpmfusion.org/).

These are dependencies I had to install:
gstreamer-plugins-base
gstreamer-plugins-good
gstreamer-plugins-bad
gstreamer-plugins-ugly
gstreamer-plugins-bad-nonfree
gnome-python2-rsvg
nautilus-python
python-gudev

Main one that isn't mentioned in README is "gstreamer-plugins-bad-nonfree" so please add it to dependency list.

**Comment by danielgtaylor** [comment]
Added in 084c253, thanks!
