### ISSUE TITLE
N900 h.264 profile not playable on device

### ISSUE THREAD

**Issue by Shnatsel** [danielgtaylor/arista#89]
Nokia N900 h.264 profile produces files not playable on the n900. I've fixed it but can's submit a fix because of https://github.com/danielgtaylor/arista/issues/88
You can get the fixed version at  http://dl.dropbox.com/u/5279564/nokia-nseries_n900-h.264-fixed.tar.bz2

**Comment by danielgtaylor** [comment]
Preset is updated, thanks!

**Comment by Shnatsel** [comment]
Still doesn't work because of these lines:

```
            "height": [
                480, 480
            ], 
            "width": [
                800, 800
            ], 
            "rate": [
                25, 25
            ]
```

Should be:

```
            "width": [
                120, 848
            ], 
            "height": [
                120, 480
            ], 
            "rate": [
                1, 30
            ]
```

**Comment by ildar** [comment]
Anyone can confirm that video converted with "N900 H.264" preset is playable with Maemo PR1.3 ?
Mine complains on unsupported format.

**Comment by Shnatsel** [comment]
The preset is NOT updated, please use my fixed one from http://dl.dropbox.com/u/5279564/nokia-nseries_n900-h.264-fixed.tar.bz2
It plays fine on my N900

**Comment by ildar** [comment]
Not in my case, see https://github.com/danielgtaylor/arista/issues/138
