### ISSUE TITLE
arista is unable to rip dvd or record webcam

### ISSUE THREAD

**Issue by guiodic** [danielgtaylor/arista#9]
arista version: 0.9.4.1
os version: ubuntu 10.04

When I try to rip a dvd or record trom webcam arista does nothing. I add to queue but nothing appears in queue list and nothing is rendered. The only result is a new directory (strangely: not file) with the name that I wrote in file chooser dialog

**Comment by alessio** [comment]
Ehya Daniel,

I can confirm this, here the bug reports already submitted to both Debian and Ubuntu:

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=555106
https://bugs.launchpad.net/arista/+bug/493270

**Comment by danielgtaylor** [comment]
Can you please try trunk and see if the issues is fixed in 13b05ab3fa3eb37e8fb8a1baa8cb3989c2cfaae1?

**Comment by guiodic** [comment]
it seems work for dvd, not webcam. Additionally, dvd ripping has a very low framerate in computer/h264 (webm works fine)

**Comment by danielgtaylor** [comment]
Confirmed the webcam issue and am trying to figure it out with the GStreamer guys.

**Comment by danielgtaylor** [comment]
Please try latest trunk again, it should fix linking issues in the pipeline for most muxers. It fixed the webcam issue for me on my Toshiba M500.

**Comment by guiodic** [comment]
yes, it works

**Comment by alessio** [comment]
Well, I'll backport the patch to Debian unstable.

**Comment by danielgtaylor** [comment]
If it helps a new release will be out in a matter of days, so you may want to wait just a few days!

**Comment by alessio** [comment]
Excellent!
