### ISSUE TITLE
Error converting in mpeg2 format (Ubuntu 11.04 + gstreamer ppa)

### ISSUE THREAD

**Issue by guiodic** [danielgtaylor/arista#93]
the error is: impossible to link lame0 to mux.
According gstreamer developers this is an application bug (but I doubt cause brasero is affected too).

**Comment by danielgtaylor** [comment]
Do other formats work? In particular, can you try Arista from git and create a new preset in Arista that uses MP3 as the audio codec and get it to work at all?

**Comment by guiodic** [comment]
I tried stable version of arista with the divx preset that uses mp3 as the audio codec. It works. The problem, I presme, is that DVDs should use mp2 or ac3. Or not?

Wikipedia says: The audio data on a DVD movie can be PCM, DTS, MPEG-1 Audio Layer II (MP2), or Dolby Digital (AC-3) format

**Comment by danielgtaylor** [comment]
Ah yeah, I can't believe I messed that up for so long and nobody else has mentioned it! Fixed in 46cbb98 and will be in the next release. Thanks for pointing it out!

**Comment by guiodic** [comment]
2011/6/16 danielgtaylor
reply@reply.github.com:

> Ah yeah, I can't believe I messed that up for so long and nobody else has mentioned it! Fixed in 46cbb98 and will be in the next release. Thanks for pointing it out!

This simply means that DVD is a obsolete media. :-)

**Comment by guiodic** [comment]
Can you upgrade the profile on website too? Thank you!
