### ISSUE TITLE
No accelerated IMDCT transform found

### ISSUE THREAD

**Issue by Pacodastre** [danielgtaylor/arista#94]
I tried to convert a mkv file containing a x264 video to DVD player with NTFS DVD as preset, and then I get this message (in console) :  No accelerated IMDCT transform found
and this message in the notification area :
Error!
Conversion of MyVideo.mpd to Generic DVD Player NTSC DVD failed! Reason: Unable to construct pipeline! could not link lame0 to mux

Thank you in advance

**Comment by danielgtaylor** [comment]
Can you upload a small sample file that has this issue somewhere so that I can reproduce and test?

**Comment by Pacodastre** [comment]
I'll try to cut some parts of my video, and I'll send it to you. Thanks for
the quick answer
Franois

2011/6/14 danielgtaylor <
reply@reply.github.com>

> Can you upload a small sample file that has this issue somewhere so that I
> can reproduce and test?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/danielgtaylor/arista/issues/94#issuecomment-1365837

## 

Ribemont Franois
ribemont.francois@gmail.com
http://ribemont.francois.free.fr

**Comment by danielgtaylor** [comment]
I've fixed some issues with the DVD presets today - can you try out Arista from git? In the preferences click the "Reset presets" button and then try making a DVD conversion.

**Comment by Pacodastre** [comment]
I get the same error.
I'll cut my video in a few minutes, and send it to you.
Paco

2011/6/16 danielgtaylor <
reply@reply.github.com>

> I've fixed some issues with the DVD presets today - can you try out Arista
> from git? In the preferences click the "Reset presets" button and then try
> making a DVD conversion.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/danielgtaylor/arista/issues/94#issuecomment-1381130

## 

Ribemont Franois
ribemont.francois@gmail.com
http://ribemont.francois.free.fr

**Comment by Pacodastre** [comment]
Is there an easy tool to use to cut videos ? I tried some of them, but doesn't seem to work well :-/

**Comment by danielgtaylor** [comment]
If the file has all the headers at the front you can use something like dd to just take the first e.g. 3-4 megabytes of the file and copy them into a new file, then send that:

```
dd if=/path/to/input of=/path/to/output bs=1024 count=4096
```

If the headers aren't at the front then the above command will create a file that refuses to play. In that case the best bet is usually to run qtfaststart (for mp4 files) or re-run the encoder that produced the file on a smaller file (or limit the number of seconds, like with -t option for ffmpeg).

**Comment by Pacodastre** [comment]
Works perfectly fine with dd.
So you can download this video for the tests :
http://share.pacodastre.org/files/test.mkv
Thanks

2011/6/16 danielgtaylor <
reply@reply.github.com>

> If the file has all the headers at the front you can use something like dd
> to just take the first e.g. 3-4 megabytes of the file and copy them into a
> new file, then send that:
> 
>    dd if=/path/to/input of=/path/to/output bs=1024 count=4096
> 
> If the headers aren't at the front then the above command will create a
> file that refuses to play. In that case the best bet is usually to run
> qtfaststart (for mp4 files) or re-run the encoder that produced the file on
> a smaller file (or limit the number of seconds, like with -t option for
> ffmpeg).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/danielgtaylor/arista/issues/94#issuecomment-1382909

## 

Ribemont Franois
ribemont.francois@gmail.com
http://ribemont.francois.free.fr

**Comment by danielgtaylor** [comment]
Thanks for the file. I was able to transcode it just fine, which leads me to believe you are still using an outdated preset! The version you need is here:
- https://github.com/danielgtaylor/arista/blob/master/presets/dvd.json

If you grab Arista from git like so in a terminal you can test:

```
git clone git://github.com/danielgtaylor/arista.git
cd arista
./arista-transcode --reset-presets
./arista-gtk
```

Does this fix your issue? It should also force an update to all installed presets that ship with Arista to the git versions, which means whatever version of Arista you have installed will now show the new presets as well.

**Comment by bg4m3r** [comment]
Hey, I just downloaded Arista today and was having the exact same issue, also with an mkv file. Followed your instructions here and am converting fine now! Thanks! :) I couldn't find anything that would convert mkv for free for Winblows!

**Comment by danielgtaylor** [comment]
Thanks for confirming the fix.
